# Generated by Django 4.2.7 on 2023-11-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244)),
                ('image', models.ImageField(upload_to='static/assets/uploads/')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='static/assets/uploads/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='static/assets/uploads/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='t_image',
            field=models.ImageField(upload_to='static/assets/uploads/'),
        ),
    ]
