# Generated by Django 4.2.7 on 2023-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0003_sponsors_alter_projects_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='year',
            field=models.DateField(default=2023),
        ),
    ]
