# Generated by Django 4.2.7 on 2023-11-17 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0004_sponsors_queue_sponsors_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(upload_to='static/assets/uploads/sponsors/'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='year',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
