# Generated by Django 4.2.7 on 2023-11-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0006_alter_sponsors_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='queue',
        ),
    ]
