# Generated by Django 4.2.7 on 2023-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0007_remove_sponsors_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(upload_to='static/assets/uploads/sponsors'),
        ),
    ]
