# Generated by Django 4.2.7 on 2023-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0008_sponsors_queue_alter_sponsors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='queue',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
