# Generated by Django 4.2.7 on 2023-11-17 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0009_alter_sponsors_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('head_image', models.ImageField(upload_to='static/assets/upload/news')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
