# Generated by Django 4.2.7 on 2023-11-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0010_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='static/assets/upload/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='static/assets/upload/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='static/assets/upload/news'),
        ),
    ]
