# Generated by Django 4.2.7 on 2023-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0011_alter_news_image_1_alter_news_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_nav',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
