# Generated by Django 4.2.7 on 2023-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0012_main_nav_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/upload/news')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_3',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, to='lf_web.image'),
        ),
    ]
