# Generated by Django 4.2.7 on 2023-11-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lf_web', '0013_image_remove_news_image_1_remove_news_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='role',
            field=models.ManyToManyField(related_name='team_members', to='lf_web.team_roles'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Belirtmek istemiyorum')], max_length=10)),
                ('parent_first_name', models.CharField(blank=True, max_length=30)),
                ('parent_last_name', models.CharField(blank=True, max_length=30)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('parent_relationship', models.CharField(blank=True, choices=[('mother', 'Anne'), ('father', 'Baba'), ('other', 'Diğer')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
