# Generated by Django 4.2.7 on 2023-12-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0015_alter_image_image_alter_news_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lf_web.news'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/assets/upload/news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='news_images', to='lf_web.image'),
        ),
    ]
