# Generated by Django 4.2.7 on 2023-12-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_web', '0017_remove_image_news_alter_image_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('school_level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
