# Generated by Django 4.2.7 on 2023-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='static/assets/uploads/academy/contents'),
        ),
    ]
