# Generated by Django 4.2.7 on 2023-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
