# Generated by Django 4.2.7 on 2023-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0005_alter_course_options_alter_level_options_level_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='menu_icon',
            field=models.CharField(default='fa-graduation-cap', max_length=100),
        ),
    ]
