# Generated by Django 4.2.7 on 2023-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0006_topic_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='menu_icon',
            field=models.CharField(default='fa-graduation-cap', max_length=100),
        ),
    ]
