# Generated by Django 4.2.7 on 2023-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0008_watchedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedcontent',
            name='watched_percentage',
            field=models.FloatField(default=0),
        ),
    ]
